import 'package:thesis_scanner/art.dart';

final artAncien = ArtCollection("Art Ancien");

final floor6 = ArtFloor("6e étage, Le regard d'un amateur", 0, 0, 35.417, 9.812, [
  ArtSection(
    "0. Introduction",
    "ciel-short.m4a",
    13.25,
    5.312,
    21.96,
    9.312,
    [],
  ), // 6.312
  ArtSection(
    "1. Oeuvres de maîtres",
    "zombie-short.m4a",
    30.85,
    0.5,
    34.917,
    9.312,
    [
      ArtPiece(
        "La ville lunaire II",
        "Paysage nocturne surnaturel de Paul Delvaux où une femme erre dans une ville étrange.",
        artAncien,
        "1956",
        "Paul Delvaux",
        ["Tableau", "Art moderne", "Peinture"],
        "Belgique",
        "https://collections-museel.s-museum.be/document/la-ville-lunaire-ii-tableau/60896a2140170b4a0c93e1ce",
        "assets/pieces/la-ville-lunaire-ii.jpg",
        null,
        3.5,
        6.5,
      ),
    ],
  ),
  ArtSection("2. Masques", "jmetire-short.m4a", 22.5, 0.5, 30.4, 9.312, [
    ArtPiece(
      "Masque de théâtre nô. Kasshiki",
      "Masque japonais du théâtre nô représentant un jeune moine, au visage énigmatique.",
      artAncien,
      "18e siècle",
      "Anonyme",
      ["Masque", "Théâtre nô", "Sculpture", "Art japonais"],
      "Japon",
      "https://collections-museel.s-museum.be/document/masque-de-theatre-no-kasshiki-masque/608a99c940170b4a0c95761d",
      "assets/pieces/masque-de-theatre-no-kasshiki.jpg",
      null,
      26,
      2,
    ),
  ]),
  ArtSection("3. Statues", "ciel-short.m4a", 13.25, 0.5, 21.96, 4.812, [
    // 3.812
    ArtPiece(
      "Tambour à fente monumental (atingting)",
      "Grand tambour en bois sculpté de Vanuatu, utilisé pour la musique et la communication.",
      artAncien,
      "vers 1950",
      "Artisan d'Ambrym",
      ["Instrument de musique", "Tambour à fente", "Idiophone"],
      "Vanuatu, île d'Ambrym",
      "https://collections-museel.s-museum.be/document/tambour-a-fente-monumental-tambour-a-fente/608a9a0c40170b4a0c9576a2",
      "assets/pieces/tambour-fente-monumental.jpg",
      null,
      8,
      2,
    ),
    ArtPiece(
      "Récipient en forme d'idole stéatopyge",
      "Statuette votive iranienne figurant une femme aux formes proéminentes, symbole de fertilité.",
      artAncien,
      "9e-8e siècle av. J.-C.",
      "Anonyme",
      ["Statuette", "Vase", "Sculpture", "Objet rituel"],
      "Iran, Guilan (Amlach/Kaluraz/Marlik?)",
      "https://collections-museel.s-museum.be/document/recipient-en-forme-d-idole-steatopyge-statuette/60894dc140170b4a0c93b0b7",
      "assets/pieces/recipent-idole-steatopyge.jpg",
      null,
      14,
      1,
    ),
  ]),
  ArtSection("4. Le paradis", "ciel-short.m4a", 0.5, 5.312, 12.75, 9.312, [
    ArtPiece(
      "Le Paradis terrestre",
      "Peinture représentant le jardin d'Éden dans une scène foisonnante et colorée.",
      artAncien,
      "XVIIe",
      "Jan Van Kessel",
      ["Tableau", "Arts plastiqes", "Peinture"],
      "Pays-Bas",
      "https://collections-museel.s-museum.be/document/le-paradis-terrestre-tableau/6089486240170b4a0c93a457",
      "assets/pieces/le-paradis-terrestre.jpg",
      null,
      2,
      5,
    ),
  ]),
]);
